### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cells')

### ISSUE THREAD

**Issue by liuxu0718** [Z-J-wang/render-juypter-notebook-vue#27]
yarn add 后
引入组件RenderJupyterNotebook 
发现控制台 报如下错误
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cells')
    at new $c (index.js:27:17)
    at Proxy.mounted (RenderJupyterNotebook.vue:14:22)
    at runtime-core.esm-bundler.js:2757:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2731:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:359:46)
    at flushJobs (runtime-core.esm-bundler.js:413:9)

**Comment by liuxu0718** [comment]
原来是因为我没导入.json文件
